#' Make the price data into returns
#'
#' This function transforms closing price data into stock returns.
#' @param data_df the data frame with stock returns
#' @param date_var date variable in quotes. Default to date_id (generated by get_close)
#' @keywords returns
#' @import magrittr
#' @import dplyr
#' @export
#' @examples
#' make_ret()

make_ret <- function( data_df, date_var = "date_id" ) {

  # make into returns
  data_df %<>%
    mutate_if(is.numeric, funs(. / lag(.) ) )

}

# make_ret <- function( data_df, date_var = "date_id" ) {
#
#   period.start <- min(data_df$date_var)  # get start date
#
#   # make into returns
#   data_df %<>%
#     mutate_if(is.numeric, funs(. / lag(.) ) ) %>%
#     filter( date_id != period.start)
#
# }

